### ISSUE TITLE
Support link token?

### ISSUE THREAD

**Issue by TristanBrotherton** [bencooper222/build-your-own-mint#28]
It looks like Plaid has depreciated public keys for link tokens. I wondered if this branch supported that, (as it wasn't in the documentation).

**Comment by TristanBrotherton** [comment]
I have managed to update the Plaid library in a fork of the original repository. However I can't make a PR for this repository as its in TypeScript which I'm not super familiar with. However I'd love to help update this to use the latest version of the Plaid sample app which would allow new users to run this code (Plaid no longer supports public keys).

**Comment by bencooper222** [comment]
Sorry about missing this! I'm not familiar with this change, do you have a link to Plaid docs on it?

**Comment by TristanBrotherton** [comment]
Hey Ben - certainly, these are the details: https://plaid.com/docs/link/maintain-legacy-integration/

**Comment by bencooper222** [comment]
ugh yeah I'll probably update this one of the next few weekends. Doesn't look too bad.
